<?php

return [
    /*
    |--------------------------------------------------------------------------
    | MARC21 Tag Definitions (Default Labels)
    |--------------------------------------------------------------------------
    */
    'tags' => [
        '001' => 'Mã biểu ghi (Control Number)',
        '003' => 'Mã tổ chức tạo biểu ghi (Control Number Identifier)',
        '005' => 'Ngày giờ cập nhật (Date/Time of Latest Transaction)',
        '008' => 'Phần tử dữ liệu cố định (Fixed-Length Data Elements)',
        '010' => 'Số kiểm soát LC (LC Control Number)',
        '020' => 'Chỉ số ISBN (International Standard Book Number)',
        '022' => 'Chỉ số ISSN (International Standard Serial Number)',
        '035' => 'Mã kiểm soát hệ thống (System Control Number)',
        '040' => 'Nguồn biên mục (Cataloging Source)',
        '041' => 'Mã ngôn ngữ (Language Code)',
        '043' => 'Mã khu vực địa lý (Geographic Area Code)',
        '050' => 'Ký hiệu xếp giá LC (LC Call Number)',
        '082' => 'Phân loại thập phân Dewey (DDC)',
        '084' => 'Mã phân loại khác (Other Classification)',
        '100' => 'Tác giả chính - Tên cá nhân (Personal Name Author)',
        '110' => 'Tác giả chính - Tên cơ quan (Corporate Name Author)',
        '111' => 'Tác giả chính - Tên hội nghị (Meeting Name Author)',
        '130' => 'Nhan đề đồng nhất chính (Uniform Title)',
        '210' => 'Nhan đề viết tắt (Abbreviated Title)',
        '222' => 'Nhan đề chính (Key Title)',
        '240' => 'Nhan đề đồng nhất (Uniform Title)',
        '245' => 'Thông tin nhan đề / Tên sách (Title Statement)',
        '246' => 'Dạng nhan đề khác (Varying Form of Title)',
        '250' => 'Thông tin lần xuất bản (Edition Statement)',
        '260' => 'Thông tin xuất bản, phát hành (Publication Info)',
        '264' => 'Thông tin sản xuất, xuất bản (Production, Publication)',
        '300' => 'Mô tả vật lý (Physical Description)',
        '336' => 'Loại nội dung (Content Type)',
        '337' => 'Loại phương tiện (Media Type)',
        '338' => 'Loại vật mang (Carrier Type)',
        '490' => 'Thông tin tên bộ / Tên sê-ri (Series Statement)',
        '500' => 'Ghi chú chung (General Note)',
        '504' => 'Ghi chú thư mục (Bibliography Note)',
        '505' => 'Ghi chú mục lục (Formatted Contents Note)',
        '520' => 'Tóm tắt nội dung (Summary)',
        '600' => 'Chủ đề - Tên cá nhân (Personal Name Subject)',
        '610' => 'Chủ đề - Tên cơ quan (Corporate Name Subject)',
        '650' => 'Chủ đề - Thuật ngữ đề mục (Topical Term Subject)',
        '651' => 'Chủ đề - Tên địa lý (Geographic Subject)',
        '653' => 'Từ khóa chỉ mục (Uncontrolled Index Term)',
        '655' => 'Thể loại / Dạng tài liệu (Genre/Form)',
        '700' => 'Tác giả phụ - Tên cá nhân (Added Entry - Personal Name)',
        '710' => 'Tác giả phụ - Tên cơ quan (Added Entry - Corporate Name)',
        '711' => 'Tác giả phụ - Tên hội nghị (Added Entry - Meeting)',
        '776' => 'Dạng vật lý khác (Additional Physical Form)',
        '800' => 'Tên bộ - Tên cá nhân (Series Added Entry)',
        '830' => 'Tên bộ - Nhan đề đồng nhất (Series Uniform Title)',
        '852' => 'Vị trí lưu trữ / Kệ sách (Location)',
        '856' => 'Đường dẫn truy cập điện tử (Electronic Location)',
        '900' => 'Dữ liệu nội bộ (Local Data 900)',
        '910' => 'Dữ liệu nội bộ (Local Data 910)',
        '920' => 'Dữ liệu nội bộ (Local Data 920)',
        '930' => 'Số đăng ký biệt cá biệt (Local Item Record)',
        '941' => 'Mã thư viện sở hữu (Library Code)',
        '942' => 'Phần tử biên mục Koha (Koha Elements)',
        '952' => 'Đăng ký tài liệu Koha (Koha Holdings)',
        '999' => 'Dữ liệu hệ thống (Local Data 999)',
    ],
];
